services:
  - type: web
    name: api-fleetguard360
    env: java
    plan: free
    branch: main
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/admin-panel-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
